### ISSUE TITLE
Getting duplicate videos on Filter and Load More

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/elliptica-on-demand#9]
If you search

- classes by Allie
- 30 minutes

One class returns. Clicking Load More will return the same class over and over.

Perhaps the solution is just to remove the Load More button when there are no more results.

I think we can use [max_num_pages](https://tommcfarlin.com/wp_query-offset/) attribute of the WP_Query or [get_max_num_pages](https://developer.wordpress.org/reference/classes/wp_sitemaps_posts/get_max_num_pages/) to track when there are more pages.

**Comment by kas5986** [comment]
ok let me check
